package com.mascotasperdidas.app.domain.model

data class PetReport(
    val id: String,
    val ownerUid: String,
    val ownerInitial: String,
    val ownerName: String = "",
    val petName: String,
    val type: ReportType,
    val breed: String,
    val species: String = "",
    val size: String = "",
    val gender: String = "",
    val color: String = "",
    val collarColor: String = "",
    val ageApprox: String = "",
    val microchip: String = "",
    val hasCollarPlate: Boolean = false,
    val hasMicrochip: Boolean = false,
    val physicalStatus: List<String> = emptyList(),
    val behaviors: List<String> = emptyList(),
    val notes: String = "",
    val description: String,
    val location: String,
    val imageUrl: String,
    val additionalPhotos: List<String> = emptyList(),
    val urgency: String = "",
    val stillInArea: Boolean = false,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val statuses: List<String> = emptyList(),
    val recencyLabel: String,
    val createdAtEpochMs: Long,
)
